### ISSUE TITLE
Bug: missing css/fonts

### ISSUE THREAD

**Issue by jsalamander** [systemli/ansible-role-mat2-web#1]
Hi there 

Not sure if this is the right place to report this:

On https://metadata.systemli.org/ the css is missing and some fonts cannot be loaded, which results in a fucked up style ;)
This is what the page should look lilke: https://api.matweb.info/

**Comment by xshadow** [comment]
Thank you. We will check the role for this.

**Comment by xshadow** [comment]
We updated the role accordingly.
