### ISSUE TITLE
mat2-web CSS builds

### ISSUE THREAD

**Issue by jsalamander** [systemli/ansible-role-mat2-web#8]
Hey there ;)

I just tagged a new mat2-web release: https://0xacab.org/jvoisin/mat2-web/-/tags/v0.6.0
The fallback UI was improved ;) Check it out here https://api.matweb.info/

As you do not use the container image you need to build the main CSS file yourselves. 
https://0xacab.org/jvoisin/mat2-web#build-the-css-file
```
npm i
npm install --global postcss postcss-cli
npm run build:css
```

Therefore I assume you must adapt your Ansible role.

**Comment by xshadow** [comment]
@jsalamander : Thanks for pointing that out. I think the following changes should be sufficient.

**Comment by jsalamander** [comment]
ping :wink: 

Anything unclear or why hasn't this been merged? :smile:

**Comment by xshadow** [comment]
After merging this, we end up mit with a broken page. Even if  `npm run build:css` was sucessful. 

The following files are missing: 
```
GEThttps://metadata.systemli.org/static/raleway.woff2
[HTTP/1.1 404 NOT FOUND 103ms]

GEThttps://metadata.systemli.org/static/script.js
[HTTP/1.1 404 NOT FOUND 212ms]

GEThttps://metadata.systemli.org/static/logo.png
[HTTP/1.1 404 NOT FOUND 202ms]

The resource from “https://metadata.systemli.org/static/script.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```


They can't be found on the server as well:
```
ls /var/www/mat2-web/mat2-web/static/
dist  favicon.png  font  logo.svg  og.png  src
```

**Comment by xshadow** [comment]
Those seems to be the previous files, I have to look into it, what goes wrong there.

**Comment by jsalamander** [comment]
sounds like some caching issue. The ls command above shows the dist folder where the newly generated  asstes should be located.

**Comment by jsalamander** [comment]
any news on this?

**Comment by xshadow** [comment]
I looked into it, but it does not seem to be a cache issue. I try to investigate during the weekend

**Comment by xshadow** [comment]
The code works fine and also worked fine in the past. But guess who shipped custom template aka an outdated version of the base.html which obviously breaks with your new styling m(.

If we use your html file everything works fine :) I will adopt ours accordingly. Thanks for the new design :) 

I updated the role in #12 , to have port forwarding when running molecule. This makes it easier to debug and pointed me directly to our mistake.

**Comment by jsalamander** [comment]
nice :) thx for debugging

**Comment by xshadow** [comment]
If you ran `molecule converge` in the role directory you have exactly what's deployed to the server on localhost:8080
